name: Lint and build test

on: 
  pull_request:
    branches:
    - main
  
  push:
    branches:
    - main

jobs:
  build-and-test:
    name: Lint and build on Ubuntu - Node 16
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install
    - run: yarn lint
    - run: yarn build
