name: Lint and build test

on: 
  pull_request:
    branches:
    - main
  
  push:
    branches:
    - main

jobs:
  build-and-test:
    name: Lint and build on Ubuntu - Node latest lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'yarn'
        check-latest: true

    - run: yarn install
    - run: yarn lint
    - run: yarn build
